/* MOQtail FFI - C bindings for FFmpeg integration */

#ifndef MOQTAIL_FFI_H
#define MOQTAIL_FFI_H

#pragma once

/* Warning: This file is autogenerated by cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define moqtail_MAX_REASON_PHRASE_LEN 1024

#define moqtail_DRAFT_11 4278190091

#define moqtail_DRAFT_14 4278190094

/**
 * Opaque handle to MOQtail client context
 */
typedef struct moqtail_moqtail_client_t {
  uint8_t _private[0];
} moqtail_moqtail_client_t;

/**
 * Opaque handle to MOQtail track context
 */
typedef struct moqtail_moqtail_track_t {
  uint8_t _private[0];
} moqtail_moqtail_track_t;

/**
 * MOQtail object for FFI
 */
typedef struct moqtail_moqtail_object_t {
  uint64_t group_id;
  uint64_t object_id;
  uint8_t publisher_priority;
  bool is_keyframe;
  uint64_t timestamp_us;
  const uint8_t *payload;
  uintptr_t payload_len;
  const uint8_t *config_data;
  uintptr_t config_len;
} moqtail_moqtail_object_t;

/**
 * Initialize MOQtail client and connect to relay
 *
 * # Safety
 * `relay_url` must be a valid null-terminated C string
 */
struct moqtail_moqtail_client_t *moqtail_client_connect(const char *relay_url,
                                                        uint64_t draft_version);

/**
 * Publish a track with WARP catalog metadata
 *
 * # Safety
 * All string pointers must be valid null-terminated C strings
 */
struct moqtail_moqtail_track_t *moqtail_publish_track(struct moqtail_moqtail_client_t *client,
                                                      const char *namespace_,
                                                      const char *track_name,
                                                      const char *catalog_json);

/**
 * Send an object to the track with LOC extensions
 *
 * # Safety
 * `track` must be a valid handle, `obj` must point to valid MoqtailObject
 */
int32_t moqtail_send_object(struct moqtail_moqtail_track_t *track,
                            const struct moqtail_moqtail_object_t *obj);

/**
 * Close track and cleanup
 *
 * # Safety
 * `track` must be a valid handle or null
 */
void moqtail_track_close(struct moqtail_moqtail_track_t *track);

/**
 * Disconnect client and cleanup
 *
 * # Safety
 * `client` must be a valid handle or null
 */
void moqtail_client_disconnect(struct moqtail_moqtail_client_t *client);

#endif  /* MOQTAIL_FFI_H */
