name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  docs:
    if: ${{ github.repository_owner == 'streaming-university' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*

      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures

      - name: Build moqtail-ts
        working-directory: libs/moqtail-ts
        run: npm run build

      - name: Create documentation
        working-directory: libs/moqtail-ts
        run: npm run docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: libs/moqtail-ts/docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
